<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Ex.Application</PackageId>
        <Authors>Ex.Application</Authors>
        <Company>Ex.Application</Company>
        <Product>Ex.Application</Product>
    </PropertyGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
      <PackageReference Include="PhoenixFramework.Core" Version="3.0.0" />
      <PackageReference Include="PhoenixFramework.Identity" Version="3.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AM.Application.Contract\AM.Application.Contract.csproj" />
      <ProjectReference Include="..\AM.Domain\AM.Domain.csproj" />
      <ProjectReference Include="..\AM.Infrastructure.Query.Contract\AM.Infrastructure.Query.Contract.csproj" />
    </ItemGroup>

</Project>
