<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Ex.Domain</PackageId>
        <Authors>Ex.Domain</Authors>
        <Company>Ex.Domain</Company>
        <Product>Ex.Domain</Product>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="PhoenixFramework.Application" Version="3.0.0" />
      <PackageReference Include="PhoenixFramework.Core" Version="3.0.0" />
      <PackageReference Include="PhoenixFramework.Domain" Version="3.0.0" />
      <PackageReference Include="PhoenixFramework.EntityFramework" Version="3.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AM.Application.Contract\AM.Application.Contract.csproj" />
    </ItemGroup>
</Project>
