<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>AM.Application.Contracts</RootNamespace>
        <PackageId>Ex.Application.Contract</PackageId>
        <Authors>Ex.Application.Contract</Authors>
        <Company>Ex.Application.Contract</Company>
        <Product>Ex.Application.Contract</Product>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="PhoenixFramework.Application" Version="3.0.0" />
      <PackageReference Include="PhoenixFramework.Company" Version="3.0.0" />
      <PackageReference Include="PhoenixFramework.Identity" Version="3.0.0" />
      <PackageReference Include="PhoenixFramework.Logging" Version="3.0.0" />
    </ItemGroup>

</Project>
