<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>AM.Application.Contracts</RootNamespace>
        <PackageId>Ex.Application.Contract</PackageId>
        <Authors>Ex.Application.Contract</Authors>
        <Company>Ex.Application.Contract</Company>
        <Product>Ex.Application.Contract</Product>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="PhoenixFramework.Application" Version="3.0.0" />
      <PackageReference Include="PhoenixFramework.Identity" Version="3.0.0" />
      <PackageReference Include="PhoenixFramework.Logging" Version="3.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="PhoenixFramework.Company">
        <HintPath>..\..\..\..\..\..\home\hossein\.nuget\packages\phoenixframework.company\2.0.3\lib\net7.0\PhoenixFramework.Company.dll</HintPath>
      </Reference>
      <Reference Include="UserManagement.Query.Contracts">
        <HintPath>..\ServiceHost\bin\Debug\net10.0\UserManagement.Query.Contracts.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
