<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Lab.Presentation.Facade.Command</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AM.Domain\AM.Domain.csproj" />
      <ProjectReference Include="..\AM.Presentation.Api\AM.Presentation.Api.csproj" />
      <ProjectReference Include="..\AM.Presentation.Facade.Contract\AM.Presentation.Facade.Contract.csproj" />
    </ItemGroup>

</Project>
