<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AM.Domain\AM.Domain.csproj" />
      <ProjectReference Include="..\AM.Presentation.Facade.Contract\AM.Presentation.Facade.Contract.csproj" />
    </ItemGroup>

</Project>
