<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AM.Application\AM.Application.csproj" />
      <ProjectReference Include="..\AM.Infrastructure.Query\AM.Infrastructure.Query.csproj" />
      <ProjectReference Include="..\AM.Infrastructure.Report.Contract\AM.Infrastructure.Report.Contract.csproj" />
      <ProjectReference Include="..\AM.Infrastructure.Report\AM.Infrastructure.Report.csproj" />
      <ProjectReference Include="..\AM.Presentation.Facade.Command\AM.Presentation.Facade.Command.csproj" />
      <ProjectReference Include="..\AM.Presentation.Facade.Query\AM.Presentation.Facade.Query.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="9.3.4" />
      <PackageReference Include="PhoenixFramework.Application" Version="3.0.0" />
      <PackageReference Include="PhoenixFramework.Autofac" Version="3.0.0" />
    </ItemGroup>

</Project>
