<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AM.Application.Contract\AM.Application.Contract.csproj" />
      <ProjectReference Include="..\AM.Infrastructure.Persist\AM.Infrastructure.Persist.csproj" />
      <ProjectReference Include="..\AM.Infrastructure.Query.Contract\AM.Infrastructure.Query.Contract.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="PhoenixFramework.Application" Version="3.0.0" />
      <PackageReference Include="PhoenixFramework.Dapper" Version="3.0.0" />
    </ItemGroup>

</Project>
